### ISSUE TITLE
サーバー移行について

### ISSUE THREAD

**Issue by tnk2tjs** [palon7/mastodon#2]
サーバーが借りられそうなので移行先決まっていなければこちらで建てることも可能です．
サーバーのスペック
- CPU  Corei5-4000番台
- メモリ  8GB
- ストレージ  1TB
- 回線  NURO光

です．自宅サーバーなので状況に応じて変更は出来ます．

**Comment by ide-an** [comment]
今のインスタンスのデータをすべて引き継ぐかどうかで難易度が変わってくると思います。
おそらく移行手順は以下のような感じかと思います。

### 引き継ぐ場合

 1. gensokyo.cloudのdb dumpを取得
    * 取得したdumpの受け渡しをどうする？
 2. 新たなmastodonインスタンスを立ち上げる
 3. db dumpを新インスタンスに投入
 4. ドメインの引き継ぎ
    * DNSサーバの構築も必要？

### 引き継がない場合

 1. 新たなmastodonインスタンスを立ち上げる
 2. 移住先をgensokyo.cloudで周知する

----

@palon7 他に対応が必要なタスクはありますでしょうか？

**Comment by tnk2tjs** [comment]
新たにインスタンスを立ち上げる方向で考えていました．

**Comment by ide-an** [comment]
引き継ぐ場合、メディアサーバのデータの引き継ぎも必要か。

**Comment by avalon-reimu** [comment]
> 取得したdumpの受け渡しをどうする？

少々強引な方法かもしれませんが、分割ZIPでアップローダーとか、
またはPalonさんがdumpをリストアする用にサーバーにアカウントを用意するとか

引き継がず新しいインスタンスを立ち上げるのが一番手軽でしょうけど、
それをやる場合は、過去ログは何かしらの方法で見れるように自分はしたいですね

**Comment by ide-an** [comment]
いったん新しいインスタンスを立てて、後からデータ移行でもいいかもしれません。
その場合、新しいインスタンスの方で一度データが（gensokyo.cloudでdumpを取った時点まで）リセットする形になりますが、まぁそこはご愛嬌ということで 😅

**Comment by y-iihoshi** [comment]
Palon さんのトゥートも読んであげて
https://gensokyo.cloud/@palon/5441154
https://gensokyo.cloud/@palon/5467315

**Comment by ide-an** [comment]
データベースの件、完全に見逃してましたね・・・。
データ移行は諦めて、新しいインスタンスでまっさらなところから始める感じですね。

**Comment by avalon-reimu** [comment]
プライバシー云々言ったら、マストドンの管理者自体、すべてのユーザーの情報の覗けるから、新しい管理者でも同じことでは？
まあ、アップローダーに分割ZIPであげるみたいな事はさすがに無しということで……（汗

**Comment by ide-an** [comment]
> 新しい管理者でも同じことでは？

アカウント登録時のメールアドレスやDMも含まれていて、それらは現管理者であるpalonさんを信用した上で渡している情報なので、他の人に渡るのはNGという判断かと。

**Comment by ide-an** [comment]
データを引き継がないとしても、LTLや投稿者本人のhomeのサルベージは別途あって良いと思います。

palonさんもそのあたりは言及してますね。
https://gensokyo.cloud/@palon/5467003
https://gensokyo.cloud/@palon/5467155
https://gensokyo.cloud/@palon/5472333

サーバ移行そのものとはまた別ものなので、別途issueを切っておきます。

**Comment by tnk2tjs** [comment]
サーバー移行の際には一から始める方向ですかね．

**Comment by avalon-reimu** [comment]
そうですね、DMとかも管理者を信用していたからこそ、コミュニケーションとして利用できていたのでしょうし、メールアドレスも、ほかの管理者公にできるものとは限らないので

**Comment by ide-an** [comment]
データ引き継ぎを考えなくていいなら、お金パワーで解決するという手もありそう。
https://jp.masto.host/
（データセンターが海外なので、墓石を回すときのタイムラグが問題になる可能性がある）

**Comment by Phroneris** [comment]
あの時誰がLTLにいて誰がいなかったかもう覚えてませんが、データの引き継ぎは全然行わずにまっさらにする、という流れ（挙がってるPalon氏のトゥートも含め）だったと思います。

**Comment by ide-an** [comment]
ここまで整理

### 確定
 * 新しいインスタンスを建てる
 * データは引き継がない

### 決まってない
 * どこにインスタンスを建てる？
    * とんかつさんサーバ
    * AWS
    * https://jp.masto.host/ で借りる
 * ドメインを引き継ぐか？

**Comment by ide-an** [comment]
ドメイン引き継ぎに関して、個人的には反対です。
 * 現gensokyo.cloudから新インスタンスへの移行期間中は両方のインスタンスが共存するので、両方で同じドメインは使えないと思われる
 * データを引き継がない以上、ドメインを引き継ぐ必然性がない

**Comment by bui5ein** [comment]
ドメイン引き継ぎについて、引き継ぎ無しに賛成です。(ドメイン名への愛着はありますが……。)

データ・アカウントを引き継がないのであれば、ドメイン引き継ぎによって、現ユーザ(特に、現在非アクティブなユーザ)への混乱が起きると考えます。

初期のリセットの際と異なり、ユーザ数が相応に増えている状態では選択できないと考えます。

**Comment by bui5ein** [comment]
インスタンスの建て先については、現在の機器構成やキャパシティ状況を知りたいところです。
(Palonさんがまとめていただいているところと思いますが)

必要とされるリソースの量によって、建て先の選択肢は狭まりますし、選択肢によっては、
新インスタンスの使い方に制約が発生すると想定されるためです。
(例えば、動画アップを手控える必要が出てくる、墓回しが現実的でなくなる、など)

**Comment by palon7** [comment]
お疲れさまです。
DBの件、先に取り上げていただいてる通りあくまで私自身に対して預けているという前提でお渡しすることはしない方針です。
そしてドメインの引き継ぎについてですが、「同ドメイン・別データ」だと認証の関係でほかのインスタンスとの接続に不具合が起きるので難しいと思われます…（最初期にリセットかけたときに実際それが原因で一部通信失敗していました）

**Comment by palon7** [comment]
現在の構成について手短にお伝えすると、
メイン: 4 Core, 4GB RAM, 50GB SSD
メディアサーバ: 3 Core, 2GB RAM, 50GB + 200GB SSD（使用率30%ほど）
となっています。
メディアサーバはS3互換のminioを利用してますが、金銭的に問題なければ本家S3を利用したほうが遙かに楽で容量等にも気を使わなくていいのでやりやすいかと！

**Comment by ANNotunzdY** [comment]
はじめまして、 https://now.kibousoft.co.jp/ などを運営しているあんのたんと申します。
もし引き継ぎ支援必要であればご連絡ください。

条件が整えば、弊社負担でAWS上で運営も可能です。
また、来年２月以降になりますが、複数のマストドンインスタンスを効率的に運用するため、データセンターにラック鯖導入も検討中です。

旧鯖アカウントでOAuth認証して、メール認証の手間無しに新鯖にアカウントを作成できる
引き継ぎの仕組みを用意してもよいかもしれませんね。

よろしくお願いします。

**Comment by syumari** [comment]
gensokyo.cloudの後継ですが鯖を用意できます。すぐにでも運用できます。
現在はmikumikudance.cloudを運営していますのである程度のノウハウはあるつもりです。
ご賛同いただければ用意させていただきます。

**Comment by syumari** [comment]
気の早い話で申し訳ありませんが、インスタンスの用意ができました。
ドメインも取得済みです。
後は、Palonさん、皆さんのご承諾を頂くのみです。

**Comment by syumari** [comment]
まずは現在ご用意できる構成です。
サーバ 2core CPU 4GB RAM 60GB SSDになります。
まずはこの構成でどのくらいストレージを消費するか様子を見させて頂きます。

急速に逼迫して足りなくなるという事であれば
1．4core CPU 8GB RAM 120GB SSDにアップグレード
2．メディアサーバとしてオブジェクトストレージを増設する
といった措置を計画しています。

**Comment by tnk2tjs** [comment]
ちなみに移行はどのタイミングで行われるのでしょうか？Palonさんがgensokyo.cloudを停止するタイミングですかね

**Comment by kelvin27315** [comment]
gensokyo.cloudで新しいインスタンスの案内もしなければならないので、停止するより前の段階で開ければ良いと思います。

**Comment by ide-an** [comment]
> gensokyo.cloudで新しいインスタンスの案内もしなければならないので、停止するより前の段階で開ければ良いと思います。

同じく先に移行したほうが良いと思います。
あと #3 で議論している投稿データサルベージのやり方によっては住民が移行した後もサルベージのための期間が必要になると思います。

**Comment by avalon-reimu** [comment]
gensokyo.cloudのユーザーからあんのたんさんへの質問を募集したのですが、しゅまりさんが引き継ぐ方向で決定するなら、質問の掲載は必要なくなりそうですがどうしましょう……😅

**Comment by ANNotunzdY** [comment]
元から居た方で可能ならそれが一番だし、しゅまりさんが引き継ぐのがよさそうですね。
自分のほうのヘルプが必要あったら、その時都度都度聞いて頂ければ。

丸ごとサーバー引き継いで、囲い込みたいとかそういう意図じゃなくて、ユーザーさんのお手伝いなので
S3だけ使いたいとか、機能修正手伝って欲しいとか、その辺もお力になれるかと。

インスタンスのほう顔出してみます。

**Comment by Phroneris** [comment]
しゅまり氏のインスタンス立てちゃいましたの件、年内というリミットでどこかしらに着地すべきな必要上、もうそのまま乗っかるのは悪くないと思います。
それで #3 の件とかに専念できるなら尚更。

**Comment by palon7** [comment]
一応、Mastodon的にインスタンスの立ち上げや運用に関しては（当然ですが）私の許可を得る必要はないので、個人の判断で自由にやっていただければと思います。
登録を受け付けられるようになり次第URLをお知らせいただければ、すべてトップページに掲載させていただきます。

**Comment by ide-an** [comment]
しゅまりさんのインスタンスが公開され、住民の移行が始まっています。
https://gensokyo.town
