### ISSUE TITLE
gensokyo.cloudの投稿データサルベージ

### ISSUE THREAD

**Issue by ide-an** [palon7/mastodon#3]
[新インスタンスへのデータ引き継ぎは行わない](https://github.com/palon7/mastodon/issues/2#issuecomment-353095635)ので、今のgensokyo.cloudへの投稿を何かしら保存できるようにしたい。

保存したいものは以下がありそう
 * LTLの内容（画像含む）
 * 自分の投稿内容（未収載、DM含む）
 * 自分がふぁぼった投稿

**Comment by kelvin27315** [comment]
LTLの内容（画像含まない）でしたら名無しV層もどきさんが持っているそうです。
自分の投稿内容に関するものは何かしらのツールを作って配布という形だと思いますが、取り出すユーザーが多いとサーバの能力的に厳しいと思います。
https://gensokyo.cloud/@desuga_nlkl5ein/5472291
https://gensokyo.cloud/@desuga_nlkl5ein/5472414
https://gensokyo.cloud/@palon/5467359

**Comment by y-iihoshi** [comment]
ふぁぼも欲しいそう
https://gensokyo.cloud/@Phroneris/5474805
https://gensokyo.cloud/@desuga_nlkl5ein/5475818

**Comment by ide-an** [comment]
LTLの内容（画像含む）については、gensokyo.cloud停止後もメディアサーバをしばらく残してもらうとすれば、名無しV層もどきさんのデータを元に作れるかと思います。

> ふぁぼ

issueに追記しておきます

**Comment by y-iihoshi** [comment]
> メディアサーバをしばらく残してもらう

その期間の金銭的負担についても俎上に載せておきたいところです（人のトゥートの威を借るウグイス（すみません））
https://gensokyo.cloud/@desuga_nlkl5ein/5476009

**Comment by ide-an** [comment]
conohaは転送量での課金はない感じですかね。
https://www.conoha.jp/pricing/?btn_id=header_pricing

エクスポート期間中のメディアサーバの運営費を計算した上で、有志でconohaカードを贈る感じでどうでしょうか。

**Comment by y-iihoshi** [comment]
停止以降も別用途で ConoHa を継続利用されるなら ConoHa カードで良いと思いますが、そうでないなら別の手段が良さそうですね。(Amazon の Wishlist?)
いずれにせよ Palon さんのご都合・お気持ちが第一ですね

added: .oO(前払いならカードで良いか)

**Comment by bui5ein** [comment]
方策を検討するにあたって、とりあえずデータ量の規模感を共有しておきます。

- 現状こちらで保持しているLTLのtoot:85万件弱
- LTLでメディアサーバを参照しているtoot:3万件台前半
- LTLから参照されているメディアサーバ上のコンテンツ数(推計):3万件台前半～13万件台前半

メディアサーバを一定期間維持していただくとして、
今月末までで、大きな増加はないと想定されるので、おおむねこの辺から維持期間の天井が見えるかなと。

**Comment by kelvin27315** [comment]
個人の投稿内容はツール配布の他に、webサービスを立ち上げてそこから取得してもらうようにする方法があると思います。
webサービスについては今のところクラウドの無料枠を使用する事を考えています。

**Comment by bui5ein** [comment]
LTLから参照されているメディアサーバ上のコンテンツ数ですが、4万件弱というところでした。
100件弱サンプリングしたところ、おおむね1件あたり平均300KB程度でした。
動画のサンプル数が少なかったので、これより上振れするかもしれませんが、
300KB * 4万件で12GB程度の量になりますね……。

**Comment by palon7** [comment]
ひとまず、2018/01/14 - 2018/02/01までは新規トゥート等を停止した上でエクスポート用にアクセスできる状態にしておきます。
もし期間的に厳しいようでしたらもう少しだけ延長することはできるかと思います。

**Comment by ide-an** [comment]
自投稿およびfavのエクスポートツールを作ってみました。
 * https://gentle-thicket-59764.herokuapp.com/
 * github https://github.com/ide-an/tootexporter

画像などのメディアのエクスポートには対応していないですが、要望があれば負荷と相談しつつ対応します。

**Comment by bui5ein** [comment]
LTLから参照されているメディアサーバ上のコンテンツ数ですが、本日時点までのLTLで45000件程度になりました。
また、同数あるプレビューファイル(1ファイルあたり50KB程度)も取得しようと思います。
最終的にデータ量は16GB程度になる見込みです。

本日08:30頃から、10並列程度で取得を始めてみようと思います。

**Comment by bui5ein** [comment]
ご連絡を漏らしておりましたが、LTLから参照されているメディアサーバ上のコンテンツ、先のレスの2017.12.24以後のものも含め、取得完了しております。
メディアサーバの維持、本当にありがとうございました。

**Comment by ide-an** [comment]
エクスポートツールの公開を終了しました。
